Repository devise-security/devise-security, pull requests merged in 2018-10, with the labels that each got.

#45 Refactor Password Expireable
  .codeclimate.yml
  .gitignore
  .mdlrc
  .rubocop.yml
  README.md
  devise-security.gemspec
  lib/devise-security.rb
  lib/devise-security/models/password_expirable.rb
  test/test_helper.rb
  test/test_password_expirable.rb
Labels: enhancement

#56 Drop support for Rails 4.1 per Rails maintenance policy
  .travis.yml
  README.md
  devise-security.gemspec
  gemfiles/rails_4.1_stable.gemfile
Labels: maintenance

#55 Remove Ruby 2.2 support
  .rubocop.yml
  devise-security.gemspec
Labels: maintenance

#52 Update README section around e-mail validation requirements
  README.md
  lib/devise-security.rb
  lib/devise-security/models/secure_validatable.rb
  lib/generators/templates/devise-security.rb
Labels: maintenance

#57 Update README.md
  README.md
Labels: maintenance

#54 Remove unnecessary locks from development dependencies
  devise-security.gemspec
Labels: dependencies, maintenance
