Repository devise-security/devise-security, pull requests merged in 2019-03, with the labels that each got.

#68 Remove mass-assignment from :password_archivable
  lib/devise-security/models/password_archivable.rb
  test/test_helper.rb
Labels: Patch, bug

#84 Add installation of imagemagick to CI so that rmagick can be unlocked
  .travis.yml
  Appraisals
  Gemfile
  README.md
  devise-security.gemspec
  gemfiles/rails_4.2_stable.gemfile
  gemfiles/rails_5.0_stable.gemfile
  gemfiles/rails_5.1_stable.gemfile
  gemfiles/rails_5.2_stable.gemfile
  gemfiles/rails_6.0_beta.gemfile
Labels: dependencies

#88 Updated German translation
  config/locales/de.yml
Labels: Minor, enhancement

#92 Bump Rails 6 to beta3
  Appraisals
Labels: dependencies
