Repository devise-security/devise-security, pull requests merged in 2019-07, with the labels that each got.

#109 check in Gemfile.lock
  .gitignore
  Gemfile.lock
Labels: :arrow_up: dependencies, :building_construction: maintenance, :hash:.:hash:.:hash: Patch

#74 Add ability to skip session limitable on a per record basis
  lib/devise-security/hooks/session_limitable.rb
  lib/devise-security/models/session_limitable.rb
  test/test_session_limitable.rb
Labels: :hash:.:hash: Minor, :sparkles: enhancement

#118 Update dependencies
  .codeclimate.yml
  .rubocop.yml
  Gemfile.lock
  devise-security.gemspec
Labels: :arrow_up: dependencies, :hash:.:hash:.:hash: Patch
