Repository devise-security/devise-security, pull requests merged in 2019-05, with the labels that each got.

#98 Cleanup session limitable
  README.md
  Rakefile
  gemfiles/rails_6.0_beta.gemfile
  lib/devise-security/hooks/session_limitable.rb
  lib/devise-security/models/compatibility/active_record.rb
  lib/devise-security/models/compatibility/mongoid.rb
  lib/devise-security/models/session_limitable.rb
  test/controllers/test_captcha_controller.rb
  test/controllers/test_password_expired_controller.rb
  test/controllers/test_security_question_controller.rb
  test/dummy/app/controllers/widgets_controller.rb
  test/dummy/config/routes.rb
  test/dummy/db/migrate/20120508165529_create_tables.rb
  test/integration/test_session_limitable_workflow.rb
  test/support/integration_helpers.rb
  test/test_helper.rb
  test/test_session_limitable.rb
Labels: Minor

#104 Fix namespace resolution problems for compatibility modules
  lib/devise-security/models/compatibility.rb
  lib/devise-security/models/compatibility/active_record_patch.rb
  lib/devise-security/models/compatibility/mongoid_patch.rb
  test/dummy/app/models/user.rb
  test/test_compatibility.rb
Labels: :bug: bug, :hash:.:hash:.:hash: Patch

#105 Bump gem version for release (0.14.2)
  lib/devise-security/version.rb
Labels: :hash:.:hash:.:hash: Patch

#107 Load Compatibility when using session limitable
  lib/devise-security/models/session_limitable.rb
  test/test_session_limitable.rb
Labels: :bug: bug, :hash:.:hash:.:hash: Patch
