Repository devise-security/devise-security, pull requests merged in 2020-05, with the labels that each got.

#200 Add minitest-rails in preparation for improving tests
  Appraisals
  Gemfile
  Gemfile.lock
  gemfiles/rails_4.2.gemfile
  gemfiles/rails_5.0.gemfile
  gemfiles/rails_5.1.gemfile
  gemfiles/rails_5.2.gemfile
  gemfiles/rails_6.0.gemfile
Labels: :arrow_up: dependencies, :hash:.:hash:.:hash: Patch, :sparkles: enhancement

#196 Add Dutch (NL) locale
  config/locales/nl.yml
  lib/generators/devise_security/install_generator.rb
  test/test_install_generator.rb
Labels: :hash:.:hash: Minor, :sparkles: enhancement

#209 Formatting of helpers.rb and Gemfile
  Gemfile
  lib/devise-security/controllers/helpers.rb
Labels: :hash:.:hash:.:hash: Patch
