Repository devise-security/devise-security, pull requests merged in 2020-04, with the labels that each got.

#189 Drop ruby 2.4 support
  .rubocop.yml
  .ruby-version
  .travis.yml
  Gemfile
  Gemfile.lock
  README.md
Labels: :arrow_up: dependencies, :building_construction: maintenance, :hash:.:hash:.:hash: Patch

#187 Updating a number of outdated dependencies
  Gemfile.lock
Labels: :arrow_up: dependencies, :hash:.:hash:.:hash: Patch

#190 Update en.yml
  config/locales/en.yml
Labels: :bug: bug, :hash:.:hash:.:hash: Patch

#178 README improvements
  README.md
Labels: :book: documentation, :hash:.:hash:.:hash: Patch

#111 Allow API responses in PasswordExpiredController
  Appraisals
  Gemfile
  Gemfile.lock
  app/controllers/devise/password_expired_controller.rb
  devise-security.gemspec
  gemfiles/rails_4.2.gemfile
  gemfiles/rails_5.0.gemfile
  gemfiles/rails_5.1.gemfile
  gemfiles/rails_5.2.gemfile
  gemfiles/rails_6.0.gemfile
  test/controllers/test_password_expired_controller.rb
  test/test_helper.rb
Labels: :bug: bug, :hash:.:hash: Minor
