Repository devise-security/devise-security, pull requests merged in 2021-12, with the labels that each got.

#358 Add solargraph-arc and update some dependencies
  .gitignore
  .ruby-version
  .solargraph.yml
  Gemfile.lock
  devise-security.gemspec
Labels: :arrow_up: dependencies, :building_construction: maintenance, :hash:.:hash:.:hash: Patch

#354 Refactor email/password check for performance
  lib/devise-security/models/secure_validatable.rb
Labels: :bug: bug, :hash:.:hash:.:hash: Patch

#361 Enable CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: :hash:.:hash:.:hash: Patch, :construction: WIP

#345 Fix translations for digits/symbols keys on password complexity
  README.md
  config/locales/en.yml
  lib/devise-security/validators/password_complexity_validator.rb
  lib/generators/templates/devise_security.rb
  test/test_complexity_validator.rb
Labels: :hash:.:hash:.:hash: Patch
