Repository devise-security/devise-security, pull requests merged in 2023-04, with the labels that each got.

#417 Update minimum ruby development version to 2.7.
  .github/workflows/test_suite.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  gemfiles/rails_5.2.gemfile
  gemfiles/rails_6.0.gemfile
  gemfiles/rails_6.1.gemfile
Labels: :arrow_up: dependencies, :hash:.:hash: Minor

#414 Fix for Devise 4.9.1
  .github/workflows/codeql-analysis.yml
  .github/workflows/test_suite.yml
  Appraisals
  README.md
  gemfiles/rails_7.0.gemfile
  lib/devise-security/models/compatibility/active_record_patch.rb
Labels: :bug: bug

#419 v0.18.0 Pre-release cleanup
  .github/workflows/test_suite.yml
  Gemfile
  Gemfile.lock
  README.md
  gemfiles/rails_5.0.gemfile
  gemfiles/rails_5.1.gemfile
  gemfiles/rails_7.0.gemfile
  lib/devise-security/version.rb
  test/dummy/config/environments/test.rb
Labels: :building_construction: maintenance, :hash:.:hash: Minor

#404 Add Rails 7.0 & Ruby 3.1 support
  .github/workflows/test_suite.yml
  Appraisals
  gemfiles/rails_6.0.gemfile
  gemfiles/rails_6.1.gemfile
  gemfiles/rails_7.0.gemfile
  test/dummy/config/application.rb
Labels: :arrow_up: dependencies, :hash:.:hash: Minor

#407 Update Mongoid to 8.0 series
  .gitignore
  Appraisals
  Brewfile
  Gemfile
  Gemfile.lock
  gemfiles/rails_5.2.gemfile
  gemfiles/rails_6.0.gemfile
  gemfiles/rails_6.1.gemfile
  gemfiles/rails_7.0.gemfile
  test/test_secure_validatable.rb
Labels: :arrow_up: dependencies
